spring.application.name=loja-web
server.port=8090

spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce?replicaSet=rs0

servicos.cep.url=http://localhost:8081/cep
servicos.produtos.url=http://localhost:8082/produtos
